export const SHOW_NEXT_QUESTION_ACTION = 'SHOW_NEXT_QUESTION_ACTION';
export const SHOW_PREV_QUESTION_ACTION = 'SHOW_PREV_QUESTION_ACTION';
export const CAR_SET_ANSWER_ACTION = 'CAR_SET_ANSWER_ACTION';
export const MANUAL_NEXT_QUESTION_ACTION = 'MANUAL_NEXT_QUESTION_ACTION';
export const MANUAL_PREV_QUESTION_ACTION = 'MANUAL_PREV_QUESTION_ACTION';
