// flow-typed signature: 2b244d2bdadbec95bc7e92dce266bd28
// flow-typed version: <<STUB>>/async-throttle_v^1.1.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-throttle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-throttle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'async-throttle/index' {
  declare module.exports: $Exports<'async-throttle'>;
}
declare module 'async-throttle/index.js' {
  declare module.exports: $Exports<'async-throttle'>;
}
