// flow-typed signature: 1ec7931688009ffd07939e6702e2b4ec
// flow-typed version: <<STUB>>/eslint-import-resolver-reactnative_v1.0.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-reactnative'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-reactnative' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-import-resolver-reactnative/index' {
  declare module.exports: $Exports<'eslint-import-resolver-reactnative'>;
}
declare module 'eslint-import-resolver-reactnative/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-reactnative'>;
}
