// flow-typed signature: e2d6be9efc44eedbbb3fc0aa1b27861b
// flow-typed version: <<STUB>>/neutrino-middleware-pwa_v^6.0.3/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'neutrino-middleware-pwa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'neutrino-middleware-pwa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'neutrino-middleware-pwa/pwa' {
  declare module.exports: any;
}

declare module 'neutrino-middleware-pwa/test/middleware_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'neutrino-middleware-pwa/index' {
  declare module.exports: $Exports<'neutrino-middleware-pwa'>;
}
declare module 'neutrino-middleware-pwa/index.js' {
  declare module.exports: $Exports<'neutrino-middleware-pwa'>;
}
declare module 'neutrino-middleware-pwa/pwa.js' {
  declare module.exports: $Exports<'neutrino-middleware-pwa/pwa'>;
}
declare module 'neutrino-middleware-pwa/test/middleware_test.js' {
  declare module.exports: $Exports<'neutrino-middleware-pwa/test/middleware_test'>;
}
