// flow-typed signature: 95517cb954b5478e8a9ff5cdae9d4f54
// flow-typed version: <<STUB>>/react-native-fade-in-view_v^1.0.4/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-fade-in-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-fade-in-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-fade-in-view/FadeInView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-fade-in-view/FadeInView.js' {
  declare module.exports: $Exports<'react-native-fade-in-view/FadeInView'>;
}
