// flow-typed signature: 681cb29b77824e055dc309de0d9b9a50
// flow-typed version: <<STUB>>/react-native-document-picker_v^1.0.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-document-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-document-picker' {
  declare module.exports: any;
}
