// flow-typed signature: 2cf7b8b4c868a6e9a67b6f6dcdac7617
// flow-typed version: <<STUB>>/react-native-picker_v^4.0.18/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-picker/index' {
  declare module.exports: $Exports<'react-native-picker'>;
}
declare module 'react-native-picker/index.js' {
  declare module.exports: $Exports<'react-native-picker'>;
}
