// flow-typed signature: 74370058933709d9696dc043dc0821c4
// flow-typed version: <<STUB>>/react-native-webview-autoheight_v^1.0.4/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-webview-autoheight'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-webview-autoheight' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-webview-autoheight/index' {
  declare module.exports: $Exports<'react-native-webview-autoheight'>;
}
declare module 'react-native-webview-autoheight/index.js' {
  declare module.exports: $Exports<'react-native-webview-autoheight'>;
}
