// flow-typed signature: cf82c459da2f342be30ad50d53dcee74
// flow-typed version: <<STUB>>/react-native-pdf-view_v^0.3.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-pdf-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-pdf-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-pdf-view/PDFView.android' {
  declare module.exports: any;
}

declare module 'react-native-pdf-view/PDFView.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-pdf-view/index' {
  declare module.exports: $Exports<'react-native-pdf-view'>;
}
declare module 'react-native-pdf-view/index.js' {
  declare module.exports: $Exports<'react-native-pdf-view'>;
}
declare module 'react-native-pdf-view/PDFView.android.js' {
  declare module.exports: $Exports<'react-native-pdf-view/PDFView.android'>;
}
declare module 'react-native-pdf-view/PDFView.ios.js' {
  declare module.exports: $Exports<'react-native-pdf-view/PDFView.ios'>;
}
