// flow-typed signature: 51736d172e9296681a2972439c73c6b1
// flow-typed version: <<STUB>>/react-native-svg-uri_v^1.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-svg-uri'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-svg-uri' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-svg-uri/test/utils' {
  declare module.exports: any;
}

declare module 'react-native-svg-uri/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-svg-uri/index' {
  declare module.exports: $Exports<'react-native-svg-uri'>;
}
declare module 'react-native-svg-uri/index.js' {
  declare module.exports: $Exports<'react-native-svg-uri'>;
}
declare module 'react-native-svg-uri/test/utils.js' {
  declare module.exports: $Exports<'react-native-svg-uri/test/utils'>;
}
declare module 'react-native-svg-uri/utils.js' {
  declare module.exports: $Exports<'react-native-svg-uri/utils'>;
}
