// flow-typed signature: c9a9321d1b101fc3f714f34965054f49
// flow-typed version: <<STUB>>/react-native-mime-types_v^2.2.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-mime-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-mime-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-mime-types/index' {
  declare module.exports: $Exports<'react-native-mime-types'>;
}
declare module 'react-native-mime-types/index.js' {
  declare module.exports: $Exports<'react-native-mime-types'>;
}
