// flow-typed signature: 5d5143098293b4cd49d8c65256007e50
// flow-typed version: <<STUB>>/react-style-proptype_v^2.0.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-style-proptype'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-style-proptype' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-style-proptype/scripts/scrape' {
  declare module.exports: any;
}

declare module 'react-style-proptype/src/__test__/index.test' {
  declare module.exports: any;
}

declare module 'react-style-proptype/src/css-properties' {
  declare module.exports: any;
}

declare module 'react-style-proptype/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-style-proptype/scripts/scrape.js' {
  declare module.exports: $Exports<'react-style-proptype/scripts/scrape'>;
}
declare module 'react-style-proptype/src/__test__/index.test.js' {
  declare module.exports: $Exports<'react-style-proptype/src/__test__/index.test'>;
}
declare module 'react-style-proptype/src/css-properties.js' {
  declare module.exports: $Exports<'react-style-proptype/src/css-properties'>;
}
declare module 'react-style-proptype/src/index.js' {
  declare module.exports: $Exports<'react-style-proptype/src/index'>;
}
