// flow-typed signature: 150eef9a4a28d58c261835811270f8b8
// flow-typed version: <<STUB>>/react-native-file-picker_v^0.0.5/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-file-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-file-picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-file-picker/Example/App' {
  declare module.exports: any;
}

declare module 'react-native-file-picker/Example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-file-picker/Example/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-file-picker/Example/App.js' {
  declare module.exports: $Exports<'react-native-file-picker/Example/App'>;
}
declare module 'react-native-file-picker/Example/index.android.js' {
  declare module.exports: $Exports<'react-native-file-picker/Example/index.android'>;
}
declare module 'react-native-file-picker/Example/index.ios.js' {
  declare module.exports: $Exports<'react-native-file-picker/Example/index.ios'>;
}
declare module 'react-native-file-picker/index' {
  declare module.exports: $Exports<'react-native-file-picker'>;
}
declare module 'react-native-file-picker/index.js' {
  declare module.exports: $Exports<'react-native-file-picker'>;
}
