// flow-typed signature: 71a7f661dc150312213668088157037f
// flow-typed version: <<STUB>>/react-native-document-picker_v^1.0.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-document-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-document-picker' {
  declare module.exports: any;
}
