// flow-typed signature: 11c0b188472ba421b19db32cb7abe163
// flow-typed version: <<STUB>>/react-collapsible_v^1.4.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-collapsible'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-collapsible' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-collapsible/dist/Collapsible' {
  declare module.exports: any;
}

declare module 'react-collapsible/gulpfile' {
  declare module.exports: any;
}

declare module 'react-collapsible/src/Collapsible' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-collapsible/dist/Collapsible.js' {
  declare module.exports: $Exports<'react-collapsible/dist/Collapsible'>;
}
declare module 'react-collapsible/gulpfile.js' {
  declare module.exports: $Exports<'react-collapsible/gulpfile'>;
}
declare module 'react-collapsible/src/Collapsible.js' {
  declare module.exports: $Exports<'react-collapsible/src/Collapsible'>;
}
