function c(name: string) {
    return `USER_DATA.${name}`;
}

export const ADDRESS_FETCH_STARTED = c('ADDRESS_FETCH_STARTED');
export const ADDRESS_FETCH_FAILED = c('ADDRESS_FETCH_FAILED');
export const ADDRESS_FETCH_FINISHED = c('ADDRESS_FETCH_FINISHED');

export const ADDRESS_ADD = c('ADDRESS_ADD');
export const ADDRESS_UPDATE = c('ADDRESS_UPDATE');
export const ADDRESS_REMOVE = c('ADDRESS_REMOVE');

export const ADDRESSES_FETCH_STARTED = c('ADDRESSES_FETCH_STARTED');
export const ADDRESSES_FETCH_FAILED = c('ADDRESSES_FETCH_FAILED');
export const ADDRESSES_FETCH_FINISHED = c('ADDRESSES_FETCH_FINISHED');
