function c(name: string) {
    return `USER_DATA.${name}`;
}

export const DOCUMENT_FETCH_STARTED = c('DOCUMENT_FETCH_STARTED');
export const DOCUMENT_FETCH_FAILED = c('DOCUMENT_FETCH_FAILED');
export const DOCUMENT_FETCH_FINISHED = c('DOCUMENT_FETCH_FINISHED');

export const DOCUMENT_ADD = c('DOCUMENT_ADD');
export const DOCUMENT_UPDATE = c('DOCUMENT_UPDATE');
export const DOCUMENT_REMOVE = c('DOCUMENT_REMOVE');

export const DOCUMENTS_ADD = c('DOCUMENTS_ADD');

export const DOCUMENTS_FETCH_STARTED = c('DOCUMENTS_FETCH_STARTED');
export const DOCUMENTS_FETCH_FAILED = c('DOCUMENTS_FETCH_FAILED');
export const DOCUMENTS_FETCH_FINISHED = c('DOCUMENTS_FETCH_FINISHED');
