export const ADD_PENDING_DOCUMENTS = 'app/documents/ADD_PENDING_DOCUMENTS';
export const REMOVE_PENDING_DOCUMENT = 'app/document/REMOVE_PENDING_DOCUMENT';
export const UPLOAD_PENDING_DOCUMENTS = 'policies/UPLOAD_PENDING_DOCUMENTS';