export const SET_DOCUMENTS = 'app/documents/ADD_DOCUMENTS';
export const ADD_PENDING_DOCUMENTS = 'app/documents/ADD_PENDING_DOCUMENTS';
export const REMOVE_PENDING_DOCUMENT = 'app/document/REMOVE_PENDING_DOCUMENT';
export const UPLOAD_PENDING_DOCUMENTS = 'app/document/UPLOAD_PENDING_DOCUMENTS';
export const SET_DOCUMENT_SUBMISSION_ERROR = 'app/document/SET_DOCUMENT_SUBMISSION_ERROR';
export const SET_IS_LOADING = 'app/document/SET_IS_LOADING';