const c = name => `quoteAddress/${name}`;

export const SET_ADDRESSES = c('SET_ADDRESSES');
export const ADD_ADDRESS = c('ADD_ADDRESS');
export const REMOVE_ADDRESS = c('REMOVE_ADDRESS');
export const UPDATE_ADDRESS = c('UPDATE_ADDRESS');
export const SET_POSSIBLE_ADDRESSES = c('SET_POSSIBLE_ADDRESSES');
export const REMOVE_POSSIBLE_ADDRESSES = c('REMOVE_POSSIBLE_ADDRESSES');

export const ADD_ADDRESS_REQUEST = c('ADD_ADDRESS_REQUEST');
export const UPDATE_ADDRESS_REQUEST = c('UPDATE_ADDRESS_REQUEST');
export const REMOVE_ADDRESS_REQUEST = c('REMOVE_ADDRESS_REQUEST');
export const SELECT_ADDRESS_REQUEST = c('SELECT_ADDRESS_REQUEST');

export const LOOKUP_POSTCODE = c('LOOKUP_POSTCODE');
export const SET_LOADING_STATE = c('SET_LOADING_STATE');

export const MOTOR_POLICY_QUOTE_ADDRESS_DETAILS_FORM = c('MOTOR_POLICY_QUOTE_ADDRESS_DETAILS_FORM');
