export const LOGIN_STARTED = 'AUTH.LOGIN_STARTED';
export const LOGIN_FINISHED = 'AUTH.LOGIN_FINISHED';
export const LOGIN_FAILED = 'AUTH.LOGIN_FAILED';
export const SET_CURRENT_USER = 'AUTH.SET_CURRENT_USER';
